# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

RUN npm ci --ignore-scripts && npm run build

# Default command
CMD ["node", "lib/index.js"]
