name: Build
permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      id-token: write  # Required for npm trusted publishing with OIDC
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Use Node.js 24
      uses: actions/setup-node@v5
      with:
        node-version: '24'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Audit
      run: npm audit --audit-level high --omit dev

    - name: Lint
      run: npm run lint

    - name: Update version
      if: github.ref_type == 'tag'
      env:
        VERSION: ${{ github.ref_name }}
      run: |
        npm version "$VERSION" --no-git-tag-version

    - name: Build
      run: |
        npm run build

    - name: Publish
      if: github.ref_type == 'tag'
      run: |
        npm publish --access public --provenance

    - name: Publish on github mcp registry
      if: github.ref_type == 'tag'
      env:
        VERSION: ${{ github.ref_name }}
      run: |
        # get homebrew in path
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install mcp-publisher@1.5.0
        mcp-publisher login github-oidc
        # patch version
        sed -i "s/{{VERSION}}/$VERSION/g" server.json
        mcp-publisher publish
        mcp-publisher logout

